---
title: Flappy parrot
hero_image: afbeeldingen / banner.png
description: Create a game in which you guide a parrot past moving obstacles
listed: true
copyedit: true
version: 4.1
last_tested: 2018-10-90
steps:
  - 
    title: Inleiding
  - 
    title: Add the pipes
  - 
    title: "Challenge: make better pipes"
    challenge: true
  - 
    title: Make the pipes move
  - 
    title: Make Flappy fall
  - 
    title: Make Flappy fly
  - 
    title: Detect collisions
  - 
    title: 'Uitdaging: meer objecten'
  - 
    title: 'Challenge: adjust the difficulty'
    challenge: true
  - 
    title: 'Challenge: add a high score'
    challenge: true
  - 
    title: 'Uitdaging: Instructie scherm'
