title: Flappy Parrot
hero_image: images/banner.png
description: Create a game in which you have to guide a parrot around scrolling pipes to score points
listed: true
copyedit: true
version: 4.1
last_tested: 2018-10-90
steps: 
- title: Introduction
- title: Add the pipes
- title: "Challenge: Make better pipes"
  challenge: true
- title: Make the pipes move
- title: Make Flappy fall
- title: Make Flappy fly
- title: Detect collision with the pipes
- title: Add scoring
- title: 'Challenge: adjust the difficulty'
  challenge: true
- title: 'Challenge: add a high score'
  challenge: true
- title: What next?